[build]
  command = "pnpm run build"
  publish = "dist-preview"

[[redirects]]
  from = "/api"
  to = "/api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
  	X-Frame-Options = "DENY"
	X-XSS-Protection = "1; mode=block"
	X-Robots-Tag = "noindex"
