[build]
  command = "pnpm run build"
  publish = "dist-preview"

[[redirects]]
  from = "/api/*"
  to = "https://try.vikunja.io/api/:splat"
  status = 200
  force = true
  headers = {X-Debug-Redirect = "api-rule"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  headers = {X-Debug-Redirect = "all-to-index"}

[[headers]]
  for = "/*"
  [headers.values]
  	X-Frame-Options = "DENY"
	  X-XSS-Protection = "1; mode=block"
	  X-Robots-Tag = "noindex"
    X-Debug = "global-debug"
